name: Codestyle and Tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master            
    - name: ESLint
      run: npm install
      
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master           
    - name: Tests
      run: docker-compose -f docker-compose.tests.yml up --abort-on-container-exit --exit-code-from tests